### ISSUE TITLE
IllegalModelAccessError when trying to run workflow

### ISSUE THREAD

**Issue by fac2003** [CampagneLaboratory/NextflowWorkbench#8]
I moved some of the samples into a writeable model and adjusted to run. The model includes a logger I found in the sample. 
jetbrains.mps.smodel.IllegalModelAccessError: You can write model only inside write actions
	at jetbrains.mps.smodel.ModelAccess.checkWriteAccess(ModelAccess.java:115)
	at jetbrains.mps.smodel.ModelAccessBase.checkWriteAccess(ModelAccessBase.java:48)
	at jetbrains.mps.smodel.AttachedNodeOwner.assertLegalChange(AttachedNodeOwner.java:81)
	at jetbrains.mps.smodel.SNode.assertCanChange(SNode.java:109)
	at jetbrains.mps.smodel.SNode.insertChildBefore(SNode.java:751)
	at jetbrains.mps.smodel.SNode.addChild(SNode.java:799)
	at jetbrains.mps.lang.smodel.generator.smodelAdapter.AbstractSNodeList$ChildrenSNodesList.doAddReference(AbstractSNodeList.java:163)
	at jetbrains.mps.lang.smodel.generator.smodelAdapter.AbstractSNodeList.addReference(AbstractSNodeList.java:38)
	at jetbrains.mps.lang.smodel.generator.smodelAdapter.AbstractSNodeList.add(AbstractSNodeList.java:140)
	at jetbrains.mps.lang.smodel.generator.smodelAdapter.AbstractSNodeList$ChildrenSNodesList.add(AbstractSNodeList.java:150)
	at jetbrains.mps.internal.collections.runtime.AbstractCollectionSequence.addElement(AbstractCollectionSequence.java:20)
	at org.campagnelab.logger.behavior.Logger__BehaviorDescriptor.add_id1EUvP1fLbE6(Unknown Source)
	at org.campagnelab.logger.behavior.Logger__BehaviorDescriptor.invokeSpecial0(Unknown Source)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeSpecial(BaseBHDescriptor.java:346)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeNonVirtualCommon(BaseBHDescriptor.java:294)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeNonVirtual(BaseBHDescriptor.java:270)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invoke(BaseBHDescriptor.java:231)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke0(SMethodImpl.java:151)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke(SMethodImpl.java:126)
	at org.campagnelab.docker.behavior.ExecuteDockerCommands.log(ExecuteDockerCommands.java:655)
	at org.campagnelab.docker.behavior.ExecuteDockerCommands.executeLsWithCache(ExecuteDockerCommands.java:731)
	at org.campagnelab.docker.bash.behavior.DockerPath__BehaviorDescriptor.doesPathExist_id2h_fDmyfOCy(DockerPath__BehaviorDescriptor.java:126)
	at org.campagnelab.docker.bash.behavior.DockerPath__BehaviorDescriptor.invokeSpecial0(DockerPath__BehaviorDescriptor.java:194)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeSpecial(BaseBHDescriptor.java:346)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeVirtual(BaseBHDescriptor.java:305)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invoke(BaseBHDescriptor.java:229)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke0(SMethodImpl.java:151)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke(SMethodImpl.java:126)
	at org.campagnelab.docker.bash.typesystem.FileDoesNotExist_NonTypesystemRule.applyRule(FileDoesNotExist_NonTypesystemRule.java:21)
	at jetbrains.mps.newTypesystem.context.typechecking.IncrementalTypechecking.applyRuleToNode(IncrementalTypechecking.java:151)
	at jetbrains.mps.newTypesystem.context.component.NonTypeSystemComponent$3.run(NonTypeSystemComponent.java:343)
	at jetbrains.mps.newTypesystem.context.typechecking.IncrementalTypechecking.runApplyRulesTo(IncrementalTypechecking.java:163)
	at jetbrains.mps.newTypesystem.context.component.NonTypeSystemComponent.applyNonTypesystemRulesToNode(NonTypeSystemComponent.java:323)
	at jetbrains.mps.newTypesystem.context.component.NonTypeSystemComponent.applyRulesToRoot(NonTypeSystemComponent.java:312)
	at jetbrains.mps.newTypesystem.context.component.NonTypeSystemComponent.access$000(NonTypeSystemComponent.java:41)
	at jetbrains.mps.newTypesystem.context.component.NonTypeSystemComponent$2.compute(NonTypeSystemComponent.java:295)
	at jetbrains.mps.newTypesystem.context.component.NonTypeSystemComponent$2.compute(NonTypeSystemComponent.java:292)
	at jetbrains.mps.languageScope.LanguageScopeExecutor.execWithModelScope(LanguageScopeExecutor.java:35)
	at jetbrains.mps.newTypesystem.context.component.NonTypeSystemComponent.applyNonTypeSystemRulesToRoot(NonTypeSystemComponent.java:292)
	at jetbrains.mps.newTypesystem.context.typechecking.IncrementalTypechecking.applyNonTypesystemRulesToRoot(IncrementalTypechecking.java:231)
	at jetbrains.mps.newTypesystem.context.typechecking.BaseTypechecking.applyNonTypesystemRulesToRoot(BaseTypechecking.java:140)
	at jetbrains.mps.newTypesystem.context.IncrementalTypecheckingContext.applyNonTypesystemRules(IncrementalTypecheckingContext.java:197)
	at jetbrains.mps.newTypesystem.context.SimpleTypecheckingContext.checkRootAndGetErrors(SimpleTypecheckingContext.java:261)
	at jetbrains.mps.typesystemEngine.checker.TypesystemChecker$1.run(TypesystemChecker.java:34)
	at jetbrains.mps.typesystem.inference.TypeContextManager$Executor.doExecute(TypeContextManager.java:266)
	at jetbrains.mps.typesystem.inference.TypeContextManager$Executor.execute(TypeContextManager.java:243)
	at jetbrains.mps.typesystem.inference.TypeContextManager.runTypeCheckingAction(TypeContextManager.java:118)
	at jetbrains.mps.typesystemEngine.checker.TypesystemChecker.getErrors(TypesystemChecker.java:32)
	at jetbrains.mps.typesystemEngine.checker.TypesystemChecker.check(TypesystemChecker.java:45)
	at jetbrains.mps.typesystemEngine.checker.TypesystemChecker.check(TypesystemChecker.java:26)
	at jetbrains.mps.checkers.IteratingChecker.check(IteratingChecker.java:86)
	at jetbrains.mps.checkers.IChecker$AbstractModelChecker$2.check(IChecker.java:63)
	at jetbrains.mps.checkers.IChecker$AbstractModelChecker$2.check(IChecker.java:53)
	at jetbrains.mps.checkers.CategoryShowingChecker.check(CategoryShowingChecker.java:39)
	at jetbrains.mps.checkers.FilteringChecker.check(FilteringChecker.java:27)
	at jetbrains.mps.checkers.CatchingChecker.check(CatchingChecker.java:25)
	at jetbrains.mps.checkers.AggregatingChecker.check(AggregatingChecker.java:26)
	at jetbrains.mps.checkers.SkippingChecker.check(SkippingChecker.java:21)
	at jetbrains.mps.checkers.ModelCheckerBuilder$1.check(ModelCheckerBuilder.java:142)
	at jetbrains.mps.checkers.ModelCheckerBuilder$1.check(ModelCheckerBuilder.java:114)
	at jetbrains.mps.ide.modelchecker.platform.actions.ModelCheckerIssueFinder$1.compute(ModelCheckerIssueFinder.java:62)
	at jetbrains.mps.ide.modelchecker.platform.actions.ModelCheckerIssueFinder$1.compute(ModelCheckerIssueFinder.java:54)
	at jetbrains.mps.util.ComputeRunnable.compute(ComputeRunnable.java:32)
	at jetbrains.mps.util.AbstractComputeRunnable.run(AbstractComputeRunnable.java:27)
	at jetbrains.mps.smodel.WorkbenchModelAccess.lambda$runReadAction$0(WorkbenchModelAccess.java:77)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:902)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:74)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:53)
	at jetbrains.mps.smodel.ModelAccessHelper.runReadAction(ModelAccessHelper.java:44)
	at jetbrains.mps.ide.modelchecker.platform.actions.ModelCheckerIssueFinder.execute(ModelCheckerIssueFinder.java:54)
	at jetbrains.mps.ide.findusages.view.UsagesView$RerunAction$1.run(UsagesView.java:332)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:565)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by fac2003** [comment]
Used logger plugin I got from Manuele:
Version 3.2
This plugin provides the org.campagnelab.logger language that provides a way to log from behavior methods into a Logger root node in a sandbox. Build number: 0

**Comment by manuelesimi** [comment]
The problem was due to some broken references in the Logger node. It has been cleaned.

**Comment by manuelesimi** [comment]
Few more fixes have been needed in order to run the embedded nextflow executable from the plugin. The new preview of the plugin is available on Dropbox and will be released soon.

**Comment by manuelesimi** [comment]
I tried to reproduce what was described in this issue: moving some processes/workflows from the plugin to a writable model in a new project and run them.

It worked (see the screen shot below). For this specific execution, Docker must be configured with at 10 GB of memory.

<img width="1118" alt="Sample Kallisto Workflow" src="https://user-images.githubusercontent.com/2822686/47030142-1a573a80-d13b-11e8-8757-380a59db6f69.png">
